name: "Create Release"

on:
  push:
    branches:
      - "develop"
      - "master"

env:
  GO_VERSION: "1.15.x"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
  
  test-windows:
    name: Test Windows
    runs-on: windows-latest
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: "Pull dependencies"
        run: go mod vendor
      - name: "Unit tests"
        run: make test
      - name: "Linter"
        run: make lint
  
  tag:
    name: Tag
    runs-on: ubuntu-latest
    needs: [test, test-windows]
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: "Calculate semver tag"
        id: semver-tag
        uses: wakatime/semver-action@v1.0.0
        with:
          prerelease_id: "alpha"
          auth_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          debug: "true"
      - name: "Create tag"
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/${{ steps.semver-tag.outputs.semver_tag }}",
              sha: context.sha
            })
      - name: Changelog
        uses: scottbrenner/generate-changelog-action@master
        id: changelog
      - name: "Create release"
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.git.createRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              tag_name: ${{ steps.semver-tag.outputs.semver_tag }},
              body: |
                ${{ steps.changelog.outputs.changelog }},
              prerelease: ${{ steps.semver-tag.outputs.is_prerelease }}
            })
