name: "Build and upload release assets"

on:
  release:
    types: [published]

env:
  GO_VERSION: "1.15.x"

jobs:
  build:
    name: Build release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build with xgo docker
        env:
          GO_VERSION: ${{ env.GO_VERSION }}
        run: ./bin/build.sh
        shell: bash
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: binaries
          path: build/
  upload:
    name: Upload release assets
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: binaries
          path: build/
      - name: Prepare release assets
        run: ./bin/prepare_assets.sh
      - name: Upload release assets
        uses: alexellis/upload-assets@0.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
        with:
          asset_paths: '["./release/*"]'
      - name: "Get the version"
        id: version
        run: echo ::set-output name=version::$(echo $GITHUB_REF | cut -d / -f 3)
      - name: "Slack notification"
        uses: 8398a7/action-slack@v3
        if: ${{ success() }}
        with:
          status: custom
          fields: message
          custom_payload: |
            {
              username: 'WakaTime Bot',
              icon_emoji: ':mega:',
              attachments: [{
                color: 'good',
                pretext: 'New <https://github.com/wakatime/wakatime-cli|wakatime-cli> version released',
                title: `${{ steps.version.outputs.version }}`,
                title_link: `https://github.com/wakatime/wakatime-cli/releases/tag/${{ steps.version.outputs.version }}`,
                text: `${process.env.AS_MESSAGE}`
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}

